export const STREAMING_LANGUAGES = {
  "af-ZA": "Afrikaans",
  "ar-AE": "Arabic (Gulf)",
  "ar-SA": "Arabic (Modern Standard)",
  "ca-ES": "Catalan",
  "cs-CZ": "Czech",
  "da-DK": "Danish",
  "de-DE": "German",
  "de-CH": "German (Swiss)",
  "el-GR": "Greek",
  "en-AB": "English (Scottish)",
  "en-AU": "English (Australian)",
  "en-GB": "English (British)",
  "en-IE": "English (Irish)",
  "en-IN": "English (Indian)",
  "en-NZ": "English (New Zealand)",
  "en-US": "English (US)",
  "en-WL": "English (Welsh)",
  "en-ZA": "English (South African)",
  "es-ES": "Spanish",
  "es-US": "Spanish (US)",
  "eu-ES": "Basque",
  "fa-IR": "Farsi",
  "fi-FI": "Finnish",
  "fr-CA": "French (Canadian)",
  "fr-FR": "French",
  "gl-ES": "Galician",
  "he-IL": "Hebrew",
  "hi-IN": "Hindi",
  "hr-HR": "Croatian",
  "id-ID": "Indonesian",
  "it-IT": "Italian",
  "ja-JP": "Japanese",
  "ko-KR": "Korean",
  "lv-LV": "Latvian",
  "ms-MY": "Malay",
  "nl-NL": "Dutch",
  "no-NO": "Norwegian Bokmål",
  "pl-PL": "Polish",
  "pt-BR": "Portuguese (Brazilian)",
  "pt-PT": "Portuguese",
  "ro-RO": "Romanian",
  "ru-RU": "Russian",
  "sk-SK": "Slovak",
  "so-SO": "Somali",
  "sr-RS": "Serbian",
  "sv-SE": "Swedish",
  "th-TH": "Thai",
  "tl-PH": "Tagalog/Filipino",
  "uk-UA": "Ukrainian",
  "vi-VN": "Vietnamese",
  "zh-CN": "Chinese (Simplified)",
  "zh-HK": "Chinese (Cantonese)",
  "zh-TW": "Chinese (Traditional)",
  "zu-ZA": "Zulu",
};
