import React, { useState } from 'react';
import { FileText, Download, Globe, AlertCircle, CheckCircle } from 'lucide-react';

interface SessionData {
  sessionId: string;
  participant: string;
  language: string;
  duration: string;
  status: string;
}

interface SummarizationReportProps {
  sessionData: SessionData;
}

const SummarizationReport: React.FC<SummarizationReportProps> = ({
  sessionData
}) => {
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [selectedLanguage, setSelectedLanguage] = useState<'en' | 'ar'>('en');
  const [summaryLength, setSummaryLength] = useState<'short' | 'medium' | 'long' | 'extra-long'>('medium');

  const API_URL = 'https://yphcka81y6.execute-api.us-east-1.amazonaws.com/prod/summarize';

  const generateSummary = async () => {
    // Hardcoded demo transcript
    const demoTranscript = `[00:00:15] Investigator: Please state your full name for the record.

[00:00:18] Witness: My name is Ahmed Al-Mahmood, I am the Chief Financial Officer at Gulf Trading Company.

[00:00:25] Investigator: Thank you. Can you describe what you discovered during the October audit?

[00:00:32] Witness: Yes. During our quarterly audit in October, I found unauthorized financial transactions. The total amount was approximately 75,000 Bahraini Dinars.

[00:00:45] Investigator: When did these transactions occur?

[00:00:50] Witness: Between July and September 2025. There were fifteen separate transfers, each between 3,000 and 8,000 BHD.

[00:01:05] Investigator: Do you know who authorized these transactions?

[00:01:10] Witness: They were not properly authorized. The transfers were made by Layla Hassan, our former Accounts Manager. She had access to the payment system.

[00:01:25] Investigator: What evidence supports this?

[00:01:30] Witness: We have bank statements, email correspondence, and system access logs showing she accessed the system after hours on multiple occasions. We also found forged approval documents.

[00:01:50] Investigator: Were there any other witnesses?

[00:01:55] Witness: Yes, Khalid Mohammed, our Internal Auditor, first detected the discrepancies during the compliance review. He can corroborate everything I have said.

[00:02:10] Investigator: Thank you. Is there anything else you would like to add?

[00:02:15] Witness: I recommend immediate action. The suspect should be apprehended, and we need to freeze her accounts and conduct a full forensic analysis.

[00:02:30] Investigator: Noted. This concludes the testimony. Session ended at 10:32 AM.`;

    setLoading(true);
    setError(null);
    setSummary(null);

    try {
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          report_text: demoTranscript,
          case_id: 'CASE-2025-001',
          session_id: sessionData.sessionId,
          user_id: 'prosecutor-202200471',
          summary_length: summaryLength,
          language: selectedLanguage
        })
      });

      const data = await response.json();

      if (response.ok) {
        setSummary(data);
      } else {
        setError(data.error || 'Failed to generate summary');
      }
    } catch (err: any) {
      setError('Failed to connect to API: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleExportWord = () => {
    if (!summary) return;

    const wordContent = `
VISION-AI INVESTIGATION SUMMARY REPORT
=====================================

SESSION DETAILS:
- Session ID: ${sessionData.sessionId}
- Witness: ${sessionData.participant}
- Duration: ${sessionData.duration}
- Status: ${sessionData.status}
- Language: ${selectedLanguage === 'en' ? 'English' : 'Arabic'}

SUMMARY:
${summary.summary}

METADATA:
- Summary ID: ${summary.summary_id}
- Case ID: ${summary.case_id}
- Generated: ${new Date().toLocaleString()}

---
Generated by Vision-AI Summarization System
Public Prosecution of Bahrain
    `;

    const blob = new Blob([wordContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Summary_${sessionData.sessionId}.doc`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportPDF = () => {
    if (!summary) return;

    const pdfContent = `
VISION-AI INVESTIGATION SUMMARY REPORT
=====================================

SESSION DETAILS:
- Session ID: ${sessionData.sessionId}
- Witness: ${sessionData.participant}
- Duration: ${sessionData.duration}
- Status: ${sessionData.status}
- Language: ${selectedLanguage === 'en' ? 'English' : 'Arabic'}

SUMMARY:
${summary.summary}

METADATA:
- Summary ID: ${summary.summary_id}
- Case ID: ${summary.case_id}
- Generated: ${new Date().toLocaleString()}

---
Generated by Vision-AI Summarization System
Public Prosecution of Bahrain
    `;

    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Summary_${sessionData.sessionId}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ padding: '24px', maxWidth: '1200px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{ 
        display: 'flex', 
        alignItems: 'center', 
        gap: '12px', 
        marginBottom: '24px',
        paddingBottom: '16px',
        borderBottom: '2px solid var(--border-light)'
      }}>
        <FileText style={{ width: '28px', height: '28px', color: 'var(--primary-color)' }} />
        <h2 style={{ fontSize: '24px', fontWeight: '600', color: 'var(--text-dark)', margin: 0 }}>
          AI-Powered Investigation Summary
        </h2>
      </div>

      {/* Session Details Card */}
      <div className="session-details-card" style={{ marginBottom: '24px' }}>
        <h3 className="details-title" style={{ 
          fontSize: '18px', 
          fontWeight: '600', 
          marginBottom: '16px',
          color: 'var(--text-dark)'
        }}>
          Session Details
        </h3>
        <div className="details-grid" style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(2, 1fr)',
          gap: '16px'
        }}>
          <div className="detail-item">
            <p className="detail-label" style={{ 
              fontSize: '14px', 
              color: 'var(--text-medium)', 
              marginBottom: '4px',
              fontWeight: '500'
            }}>
              Session ID:
            </p>
            <p className="detail-value" style={{ 
              fontSize: '16px', 
              color: 'var(--text-dark)', 
              fontWeight: '600' 
            }}>
              {sessionData.sessionId}
            </p>
          </div>
          <div className="detail-item">
            <p className="detail-label" style={{ 
              fontSize: '14px', 
              color: 'var(--text-medium)', 
              marginBottom: '4px',
              fontWeight: '500'
            }}>
              Duration:
            </p>
            <p className="detail-value" style={{ 
              fontSize: '16px', 
              color: 'var(--text-dark)', 
              fontWeight: '600' 
            }}>
              {sessionData.duration}
            </p>
          </div>
          <div className="detail-item">
            <p className="detail-label" style={{ 
              fontSize: '14px', 
              color: 'var(--text-medium)', 
              marginBottom: '4px',
              fontWeight: '500'
            }}>
              Witness:
            </p>
            <p className="detail-value" style={{ 
              fontSize: '16px', 
              color: 'var(--text-dark)', 
              fontWeight: '600' 
            }}>
              {sessionData.participant}
            </p>
          </div>
          <div className="detail-item">
            <p className="detail-label" style={{ 
              fontSize: '14px', 
              color: 'var(--text-medium)', 
              marginBottom: '4px',
              fontWeight: '500'
            }}>
              Status:
            </p>
            <p style={{ 
              fontSize: '16px', 
              color: sessionData.status === 'Completed' ? '#10b981' : '#f59e0b',
              fontWeight: '600',
              display: 'flex',
              alignItems: 'center',
              gap: '6px'
            }}>
              <CheckCircle style={{ width: '18px', height: '18px' }} />
              {sessionData.status}
            </p>
          </div>
        </div>
      </div>

      {/* Customization Options */}
      <div style={{ 
        background: 'var(--background-light)', 
        padding: '24px', 
        borderRadius: '12px',
        marginBottom: '24px'
      }}>
        <h3 style={{ 
          fontSize: '18px', 
          fontWeight: '600', 
          color: 'var(--text-dark)',
          marginBottom: '20px'
        }}>
          Summary Customization
        </h3>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '20px' }}>
          {/* Language Selection */}
          <div>
            <label style={{ 
              display: 'block', 
              fontSize: '14px', 
              fontWeight: '600', 
              color: 'var(--text-dark)',
              marginBottom: '8px'
            }}>
              <Globe style={{ width: '16px', height: '16px', display: 'inline', marginRight: '6px' }} />
              Summary Language
            </label>
            <select 
              value={selectedLanguage}
              onChange={(e) => setSelectedLanguage(e.target.value as 'en' | 'ar')}
              style={{
                width: '100%',
                padding: '12px',
                border: '1px solid var(--border-medium)',
                borderRadius: '8px',
                fontSize: '14px',
                color: 'var(--text-dark)',
                backgroundColor: 'var(--background-white)',
                cursor: 'pointer'
              }}
            >
              <option value="en">English</option>
              <option value="ar">Arabic (العربية)</option>
            </select>
          </div>

          {/* Summary Length */}
          <div>
            <label style={{ 
              display: 'block', 
              fontSize: '14px', 
              fontWeight: '600', 
              color: 'var(--text-dark)',
              marginBottom: '8px'
            }}>
              Summary Length
            </label>
            <select 
              value={summaryLength}
              onChange={(e) => setSummaryLength(e.target.value as 'short' | 'medium' | 'long' | 'extra-long')}
              style={{
                width: '100%',
                padding: '12px',
                border: '1px solid var(--border-medium)',
                borderRadius: '8px',
                fontSize: '14px',
                color: 'var(--text-dark)',
                backgroundColor: 'var(--background-white)',
                cursor: 'pointer'
              }}
            >
              <option value="short">Short (100-150 words)</option>
              <option value="medium">Medium (200-300 words)</option>
              <option value="long">Long (400-500 words)</option>
              <option value="extra-long">Extra Long (600-800 words)</option>
            </select>
          </div>
        </div>

        {/* Generate Button */}
        <button 
          className="btn btn-primary"
          onClick={generateSummary}
          disabled={loading}
          style={{ 
            width: '100%', 
            justifyContent: 'center',
            marginTop: '20px',
            padding: '14px',
            fontSize: '16px',
            fontWeight: '600',
            backgroundColor: '#1e3a8a',
            borderColor: '#1e3a8a'
          }}
        >
          <FileText className="btn-icon" />
          <span>{loading ? 'Generating Summary...' : 'Generate Summary'}</span>
        </button>

      </div>

      {/* Loading State */}
      {loading && (
        <div style={{ 
          textAlign: 'center', 
          padding: '40px',
          background: 'var(--background-light)',
          borderRadius: '12px',
          marginBottom: '24px'
        }}>
          <div style={{
            border: '4px solid var(--border-light)',
            borderTop: '4px solid var(--primary-color)',
            borderRadius: '50%',
            width: '50px',
            height: '50px',
            animation: 'spin 1s linear infinite',
            margin: '0 auto 20px'
          }}></div>
          <p style={{ color: 'var(--text-dark)', fontWeight: '600', fontSize: '16px' }}>
            Generating AI-powered summary...
          </p>
          <p style={{ color: 'var(--text-medium)', fontSize: '14px', marginTop: '8px' }}>
            Analyzing session content with Amazon Bedrock Nova Lite
          </p>
        </div>
      )}

      {/* Error State */}
      {error && (
        <div style={{
          background: '#fee',
          border: '2px solid #c53030',
          color: '#c53030',
          padding: '16px',
          borderRadius: '8px',
          marginBottom: '24px',
          display: 'flex',
          alignItems: 'center',
          gap: '12px'
        }}>
          <AlertCircle style={{ width: '20px', height: '20px' }} />
          <div>
            <strong>Error:</strong> {error}
          </div>
        </div>
      )}

      {/* Summary Results */}
      {summary && !loading && (
        <div style={{ marginTop: '24px' }}>
          {/* Summary Content */}
          <div style={{
            background: 'var(--background-white)',
            border: '2px solid var(--border-light)',
            borderRadius: '12px',
            padding: '24px',
            marginBottom: '24px'
          }}>
            <h3 style={{ 
              fontSize: '18px', 
              fontWeight: '600', 
              color: 'var(--text-dark)',
              marginBottom: '16px',
              display: 'flex',
              alignItems: 'center',
              gap: '8px'
            }}>
              <CheckCircle style={{ width: '20px', height: '20px', color: '#10b981' }} />
              Generated Summary
            </h3>
            <div style={{
              background: 'var(--background-light)',
              padding: '20px',
              borderRadius: '8px',
              lineHeight: '1.8',
              color: 'var(--text-dark)',
              fontSize: '15px',
              direction: selectedLanguage === 'ar' ? 'rtl' : 'ltr',
              textAlign: selectedLanguage === 'ar' ? 'right' : 'left'
            }}>
              {summary.summary}
            </div>
          </div>

          {/* Summary Metadata */}
          <div className="session-details-card" style={{ marginBottom: '24px' }}>
            <h3 className="details-title" style={{ 
              fontSize: '16px', 
              fontWeight: '600', 
              marginBottom: '16px',
              color: 'var(--text-dark)'
            }}>
              Summary Metadata
            </h3>
            <div className="details-grid" style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(3, 1fr)',
              gap: '16px'
            }}>
              <div className="detail-item">
                <p className="detail-label" style={{ 
                  fontSize: '14px', 
                  color: 'var(--text-medium)', 
                  marginBottom: '4px' 
                }}>
                  Summary ID:
                </p>
                <p className="detail-value" style={{ 
                  fontSize: '14px', 
                  color: 'var(--text-dark)', 
                  fontWeight: '600',
                  fontFamily: 'monospace'
                }}>
                  {summary.summary_id}
                </p>
              </div>
              <div className="detail-item">
                <p className="detail-label" style={{ 
                  fontSize: '14px', 
                  color: 'var(--text-medium)', 
                  marginBottom: '4px' 
                }}>
                  Case ID:
                </p>
                <p className="detail-value" style={{ 
                  fontSize: '14px', 
                  color: 'var(--text-dark)', 
                  fontWeight: '600' 
                }}>
                  {summary.case_id}
                </p>
              </div>
              <div className="detail-item">
                <p className="detail-label" style={{ 
                  fontSize: '14px', 
                  color: 'var(--text-medium)', 
                  marginBottom: '4px' 
                }}>
                  Language:
                </p>
                <p className="detail-value" style={{ 
                  fontSize: '14px', 
                  color: 'var(--text-dark)', 
                  fontWeight: '600' 
                }}>
                  {selectedLanguage === 'en' ? 'English' : 'العربية'}
                </p>
              </div>
            </div>
          </div>

          {/* Export Buttons */}
          <div style={{ 
            display: 'grid', 
            gridTemplateColumns: 'repeat(2, 1fr)', 
            gap: '16px' 
          }}>
            <button 
              className="action-btn primary"
              onClick={handleExportWord}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px',
                padding: '14px'
              }}
            >
              <Download className="btn-icon" />
              <span>Export as Word</span>
            </button>
            <button 
              className="action-btn primary"
              onClick={handleExportPDF}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px',
                padding: '14px'
              }}
            >
              <Download className="btn-icon" />
              <span>Export as PDF</span>
            </button>
          </div>
        </div>
      )}

      <style>{`
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
};

export default SummarizationReport;